import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../globals/styles/style.color.css";
import ThemeProvider from "@/app/context/ThemeProvider";
import { ToastContainer } from "react-toastify";


import ReactQueryProvider from "./providers/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased primary-bg overflow-x-hidden` }
        suppressHydrationWarning 
      >
        <ToastContainer position="top-center" />
        <ThemeProvider> 
          <ReactQueryProvider>
           {children}        
            </ReactQueryProvider>    
        </ThemeProvider>
      </body>
    </html>
  );
}
