import {Job} from "./types"

export const jobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "Cv Saathi Pvt Ltd",
    category: "Development",
    location: "Ghattekulo",
    experienceYears: 5,
    experienceLabel: "5+ years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "Negotiable",
    openings: 3,
    deadline: "2025-12-03",
    postedDate: "2025-11-05",
  },
  {
    id: "2",
    title: "Mid-level React Developer",
    company: "PixelCraft Labs",
    category: "Development",
    location: "Remote",
    experienceYears: 3,
    experienceLabel: "3+ years",
    positionType: "Full-Time",
    isOnsite: false,
    salary: "₹80,000 - ₹100,000 / month",
    openings: 2,
    deadline: "2025-12-15",
    postedDate: "2025-11-20",
  },
  {
    id: "3",
    title: "Junior Frontend Engineer1",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "4",
    title: "Junior Frontend Engineer2",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "5",
    title: "Junior Frontend Engineer3",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "6",
    title: "Junior Frontend Engineer4",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "7",
    title: "Junior Frontend Engineer5",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "8",
    title: "Junior Frontend Engineer6",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "9",
    title: "Junior Frontend Engineer7",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
   {
    id: "10",
    title: "Junior Frontend Engineer8",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
   {
    id: "11",
    title: "Junior Frontend Engineer9",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  },
  {
    id: "12",
    title: "Junior Frontend Engineer10",
    company: "DevForge Studios",
    category: "Development",
    location: "Kathmandu",
    experienceYears: 1,
    experienceLabel: "1–2 years",
    positionType: "Full-Time",
    isOnsite: true,
    salary: "₹40,000 - ₹60,000 / month",
    openings: 4,
    deadline: "2025-12-10",
    postedDate: "2025-11-18",
  }
  
  
  
];